  <!--
      WARNING - @mcggenerated
      This element is automatically generated by MCG Generator, do not modify.
      This element was generated on ${.now?date}.
    -->
  <select id="getData" resultMap="BaseResultMap" parameterType="${params.packageMap["SqlBean"]}">
      SELECT t.* 
        FROM ${table.tableName} t
       WHERE (1=1) 
             ${r"${condition}"}
       order by ${r"${orderby}"}
  </select>